#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Sync Code from eSir Autobuild Script

# Add a button to trigger the workflow - Kuroko
on: 
  repository_dispatch:
  workflow_dispatch:
  
  push:
    branches: 
      - master

#  schedule:
#    - cron: 0 19 * * *

jobs:

  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Syncing Preparation
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Start Syncing Autobuild Most Updated Changes
      run: git pull https://github.com/esirplayground/AutoBuild-OpenWrt.git --log --no-commit

    - name: Download All New Changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi
        
    - name: Update My Script
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH
